valuesFilePath: ./values.yml

resources:
  # - name: app_repo
  #   type: GitRepo
  #   configuration:
  #     gitProvider: {{ .Values.myRepo.gitProvider }}
  #     path: {{ .Values.myRepo.path }}
  #     branches:
  #       include: master

  - name: pre_promoted_buildinfo
    type: BuildInfo
    configuration:
      sourceArtifactory: {{ .Values.myRepo.artifactory }}
      buildName: venortso_npm
      buildNumber: 3

  - name: promoted_buildinfo
    type: BuildInfo
    configuration:
      sourceArtifactory: {{ .Values.myRepo.artifactory }}
      buildName: npm_build
      buildNumber: 1.0.1

pipelines:
  - name: venortso_npm_promote
    steps:
      - name: fetch_conditions
        type: Bash
        configuration:
          inputResources:
          - name: GitRepo
            trigger: false
        execution:
            onExecute:
              - echo "Running Bash"
              - add_run_variables promote="true"
            onComplete:
                - echo "promote = ${promote}"
                 
      - name: promote
        type: PromoteBuild
        configuration:
          condition: promote == "true"
          #inherits all the tags from bash
          targetRepository: {{ .Values.myRepo.targetRepo }}
          includeDependencies:  false
          status:  "success"
          comment: "Promoting to 1.0.1"
          inputSteps:
              - name: fetch_conditions
          inputResources:
            - name: pre_promoted_buildinfo   # required
          outputResources:
            - name: promoted_buildinfo   # required

        execution:
          onStart:
            - echo "Preparing for work..."
          onSuccess:
            - echo "Job well done!"
          onFailure:
            - echo "uh oh, something went wrong"
          onComplete: #always
            - echo "Cleaning up some stuff"